title: "Pranay Reddy Patlolla"
description: Phone Number- 313-318-4958 | Email- patlolla905@gmail.com | LinkedIn- <a href="https://www.linkedin.com/in/pranaypr/"_blank">pranaypr</a>
logo: assets/img/headshot.jpg
 description: **<a href="assets/img/About.png"_blank">ABOUT ME</a>**
theme: jekyll-theme-minimal
