title: "Pranay Reddy Patlolla"
description: <a href="assets/img/me.pdf" target="_blank">About Me</a> | Phone Number- 313-318-4958 | Email- patlolla905@gmail.com | LinkedIn- <a href="https://www.linkedin.com/in/pranaypr/"_blank">pranaypr</a>
logo: assets/img/headshot.jpg
theme: jekyll-theme-minimal
