title: Pranay Reddy Patlolla
logo: /assets/img/headshot.jpg
description: Phone- 313-318-4958 | Email- patlolla905@gmail.com | LinkedIn- <a href="https://www.linkedin.com/in/pranaypr/"_blank">pranaypr</a>
description: 
# show_downloads: true
theme: jekyll-theme-minimal
