title: "Pranay Reddy Patlolla"
logo: "/assets/img/headshot.jpg"
description_about_me: <a href='assets/img/me.pdf' target='_blank'>About Me</a>
description : Phone Number- 313-318-4958 | Email- patlolla905@gmail.com | LinkedIn- <a href='https://www.linkedin.com/in/pranaypr/' target='_blank'>pranaypr</a>
theme: jekyll-theme-minimal
