title: "Manideep Gongalla"
logo: "assets/img/IMG_5512.jpeg"
description : Phone Number- 716-449-8884 | Email- manideepgonglla@gmail.com | <a href='https://www.linkedin.com/in/manidep-g/' target='_blank'>LinkedIn</a>
theme: jekyll-theme-minimal
